### ISSUE TITLE
[BUG] Charts won't get consistently deleted

### ISSUE THREAD

**Issue by rehtlaw** [tillvit/smeditor#139] opened 2024-10-01 15:20 UTC
**Version/OS**
1.0.0 Linux

**Describe the bug**
Deleting charts isn't actually consistent. As far as I can tell, if you delete a chart that's in a slot higher (or I guess lower? more difficult) than the chart you have selected and saved on, it may just... not actually get deleted after you save and reload the file again. The Challenge chart seems to do this the most, but it can happen with others as well.

**To Reproduce**
- grab a simfile with multiple charts in a gamemode (preferably with all 5 difficulties)
- delete every difficulty except for one (for example the medium chart)
- save the simfile and open it again, either in SMEditor or anything else that can read simfiles and check the difficulty slots

**Comment by tillvit** [comment] 2024-10-07 18:37
Fixed in next update; was caused by writing to a file not clearing the previous contents past the written length.

**Closed by tillvit** 2024-10-07 18:37 UTC
Labels: bug, app, priority: high
